### ISSUE TITLE
Retrieving attribute values in Oga can be done easier

### ISSUE THREAD

**Issue by yorickpeterse** [jonahb/rpath#1]
See https://github.com/jonahb/rpath/blob/1353bc26973e8d09b3fdc29632a9afba11eaf954/lib/rpath/adapters/oga.rb#L36

Instead of this:

``` ruby
attr = vertex.attr(name)
attr && attr.value
```

You can just do this instead:

``` ruby
vertex.get(name)
```

This will return the attribute value as a String, nil otherwise (http://code.yorickpeterse.com/oga/latest/Oga/XML/Element.html#get-instance_method)

**Comment by jonahb** [comment]
@YorickPeterse thanks for the tip!
